import {redirect} from 'next/navigation';import {createServerClient} from '@supabase/ssr';import {cookies} from 'next/headers';import {adminDb} from '@/lib/supabase';import {DeleteApprovedStory} from '@/components/DeleteApprovedStory';import {moderate,saveNotificationTemplates,toggleDisplay,updateStory} from './actions';
export const dynamic='force-dynamic';
const defaults={approved:{subject:'Congratulations! Your story was approved.',body:'Thank you for sharing your Unbelievable Coincidence story. It now joins the others at {{story_url}} where it can be marveled at and rated.'},rejected:{subject:'Sorry. Your story was not accepted.',body:'The story you submitted, while it was undoubtedly unbelievable or full of coincidence, did not meet our high standards.\n\nJust a reminder that stories involving fortunetellers, games of chance, or merely weird or profoundly headscratching incidents do not conceptually qualify.\n\nIn cases of the extreme unbelievability, Unbelievable Coincidence management may request witnesses or other forms of documentation to validate the unbelievablosity and/or coincidentality.'}};
export default async function Admin(){
  const jar=await cookies();const supabase=createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{cookies:{getAll:()=>jar.getAll(),setAll:()=>{}}});const {data:{user}}=await supabase.auth.getUser();if(!user||user.email?.toLowerCase()!==(process.env.OWNER_EMAIL||'gtrueman@gmail.com').toLowerCase())redirect('/login');
  const db=adminDb();await db.rpc('purge_expired_submitter_data');
  const [{data:pending},{data:approved},{data:templateRows},{data:emailLog}]=await Promise.all([db.from('submissions').select('id,title,byline,email,body,verified_at').eq('status','pending_review').order('verified_at',{ascending:true}),db.from('stories').select('id,title,byline,body,display,published_at,rating_count,rating_total').order('published_at',{ascending:false}),db.from('notification_templates').select('kind,subject,body'),db.from('decision_email_log').select('id,decision,subject,recipient_masked,delivery_status,sent_at').order('sent_at',{ascending:false}).limit(100)]);
  const templates={...defaults};for(const row of templateRows||[]){const kind=row.kind as 'approved'|'rejected';if(kind==='approved'||kind==='rejected')templates[kind]={subject:row.subject,body:row.body};}
  return <main className="admin"><h1>Submissions</h1>
    <section className="admin-section"><h2>Waiting for review</h2>{!pending?.length&&<p>Nothing is waiting for review.</p>}{pending?.map(s=><article key={s.id}><div className="eyebrow">Verified submission</div><h3>{s.title}</h3><p>{s.byline} · {s.email}</p><div className="story-body">{s.body}</div><div className="decision-options">{(['approved','rejected'] as const).map(kind=><details className="decision" key={kind}><summary>{kind==='approved'?'Approve and prepare email':'Reject and prepare email'}</summary><form action={moderate} className="decision-form"><input type="hidden" name="id" value={s.id}/><input type="hidden" name="action" value={kind==='approved'?'approve':'reject'}/><label>Subject<input name="subject" defaultValue={templates[kind].subject} required maxLength={200}/></label><label>Message<textarea name="message" defaultValue={templates[kind].body} required maxLength={5000} rows={kind==='approved'?6:12}/></label><p className="form-help">Edit this individual message if desired. Placeholders: {'{{story_title}}'}, {'{{story_url}}'}, {'{{site_url}}'}.</p><button className={kind==='rejected'?'secondary':''}>{kind==='approved'?'Approve, publish & send':'Reject & send'}</button></form></details>)}</div></article>)}</section>
    <section className="admin-section"><h2>Approved submissions</h2>{approved?.map(s=><details className="approved-item" key={s.id}><summary><form action={toggleDisplay}><input type="hidden" name="id" value={s.id}/><input type="hidden" name="display" value={String(!s.display)}/><button className={`display-check ${s.display?'checked':''}`} aria-label={s.display?'Hide story':'Display story'} title={s.display?'Displayed publicly — click to hide':'Hidden — click to display'}>{s.display?'✓':''}</button></form><span>{s.title}</span><small>{s.display?'Displayed':'Hidden'} · {s.rating_count||0} ratings</small></summary><form action={updateStory} className="edit-story"><input type="hidden" name="id" value={s.id}/><label>Title<input name="title" defaultValue={s.title} required maxLength={80}/></label><label>Submitted by<input name="byline" defaultValue={s.byline} required maxLength={60}/></label><label>Story text <span>Paragraph breaks and line breaks are preserved.</span><textarea name="body" defaultValue={s.body} required maxLength={8000} rows={18}/></label><button>Save changes</button></form><DeleteApprovedStory id={s.id} title={s.title}/></details>)}</section>
    <section className="admin-section template-settings"><h2>Decision email defaults</h2><p>These become the starting text for each decision. You can still edit an individual email before sending it.</p><form action={saveNotificationTemplates}>{(['approved','rejected'] as const).map(kind=><fieldset key={kind}><legend>{kind==='approved'?'Acceptance':'Rejection'} email</legend><label>Subject<input name={`${kind}_subject`} defaultValue={templates[kind].subject} required maxLength={200}/></label><label>Message<textarea name={`${kind}_body`} defaultValue={templates[kind].body} required maxLength={5000} rows={kind==='approved'?5:12}/></label></fieldset>)}<p className="form-help">Available placeholders: {'{{story_title}}'}, {'{{story_url}}'}, {'{{site_url}}'}.</p><button>Save email defaults</button></form></section>
    <section className="admin-section"><h2>Decision email history</h2><p className="form-help">This retains delivery facts, not full addresses or message bodies. The newest 100 entries are shown.</p>{!emailLog?.length?<p>No decision emails have been recorded.</p>:<div className="email-log">{emailLog.map(row=><div key={row.id}><span>{new Date(row.sent_at).toLocaleDateString()}</span><b>{row.decision}</b><span>{row.recipient_masked}</span><span>{row.delivery_status}</span><small>{row.subject}</small></div>)}</div>}</section>
  </main>;
}
