'use client';
import {useMemo,useState} from 'react';import Link from 'next/link';import type {Story} from '@/lib/supabase';import {Rating} from '@/components/Rating';

function average(s:Story){return s.rating_count?s.rating_total/s.rating_count:0}
function date(value:string){return new Intl.DateTimeFormat('en-US',{month:'2-digit',day:'2-digit',year:'2-digit'}).format(new Date(value)).replaceAll('/','.')}
function excerpt(body:string,max=250){if(body.length<=max)return body;const slice=body.slice(0,max+1);const lastSpace=slice.lastIndexOf(' ');return `${body.slice(0,lastSpace>0?lastSpace:max).trimEnd()}…`}
function Meta({story}:{story:Story}){return <p className="story-meta">Submitted by {story.byline} <span>|</span> Date: {date(story.published_at)} <span>|</span> Rated: {story.rating_count||0} <span>|</span> Average Rating: {story.rating_count?average(story).toFixed(1):'—'}</p>}

export function StoryShell({stories,featured}:{stories:Story[],featured?:Story}){
  const [sort,setSort]=useState<'recent'|'rated'>('recent');const sorted=useMemo(()=>[...stories].sort((a,b)=>sort==='recent'?new Date(b.published_at).getTime()-new Date(a.published_at).getTime():average(b)-average(a)||b.rating_count-a.rating_count||new Date(b.published_at).getTime()-new Date(a.published_at).getTime()),[stories,sort]);
  const archiveLabel=`${stories.length.toLocaleString()} ${stories.length===1?'story':'stories'} in the archive`;
  return <main className="story-grid"><aside className="index" id="story-list"><div className="archive-heading"><div className="eyebrow">The stories</div><span>{archiveLabel}</span></div><div className="sort-links"><button className={sort==='recent'?'active':''} onClick={()=>setSort('recent')}>Most Recent</button><span>|</span><button className={sort==='rated'?'active':''} onClick={()=>setSort('rated')}>Highest Rated</button></div><nav>{sorted.map(s=><Link key={s.id} href={`/stories/${s.slug}`}><span>{String(s.archive_number).padStart(2,'0')}</span><span className="index-story"><b>{s.title}</b><small>Submitted by {s.byline} | Date: {date(s.published_at)} | Rated: {s.rating_count||0} | Average Rating: {s.rating_count?average(s).toFixed(1):'—'}</small></span></Link>)}</nav><Link href="/submit" className="submit-link">Tell us your story <b>→</b></Link></aside><article className="feature"><a href="#story-list" className="story-list-link">View story list <b>→</b></a>{featured?<><div className="eyebrow">A story selected by chance</div><h1>{featured.title}</h1><Meta story={featured}/><div className="story-body"><p>{excerpt(featured.body)}</p>{featured.body.length>250&&<Link href={`/stories/${featured.slug}`} className="read-more">read more</Link>}</div><Rating storyId={featured.id} initialCount={featured.rating_count||0} initialTotal={featured.rating_total||0}/></>:<div className="empty"><div className="eyebrow">The first coincidence awaits</div><h1>A curious beginning</h1><p>True stories will appear here after they have been submitted, verified, and approved.</p></div>}</article></main>;
}
